{"status":"OK","subtests":[{"name":"keys(): .next() on empty means forever done, even if you set more","status":"PASS"},{"name":"keys(): for-await-of loop body never executes","status":"PASS"},{"name":"keys(): error path: returns new rejected promises, each with the same reason","status":"PASS"},{"name":"values(): .next() on empty means forever done, even if you set more","status":"PASS"},{"name":"values(): for-await-of loop body never executes","status":"PASS"},{"name":"values(): error path: returns new rejected promises, each with the same reason","status":"PASS"},{"name":"entries(): .next() on empty means forever done, even if you set more","status":"PASS"},{"name":"entries(): for-await-of loop body never executes","status":"PASS"},{"name":"entries(): error path: returns new rejected promises, each with the same reason","status":"PASS"}]}